### ISSUE TITLE
RuntimeError: Input type (float) and bias type (c10::Half) should be the same

### ISSUE THREAD

**Issue by howardgriffin** [shunk031/training-free-structured-diffusion-guidance#10]
Traceback (most recent call last):
  File "test.py", line 7, in <module>
    image = pipe(prompt, struct_attention="align_seq").images[0]
  File "/opt/anaconda3/envs/ldm/lib/python3.8/site-packages/torch/autograd/grad_mode.py", line 27, in decorate_context
    return func(*args, **kwargs)
  File "/data/vjuicefs_hz_cv_enhance_v1/11103392/code/ldm/training-free-structured-diffusion-guidance/tfsdg/pipelines/tfsdg_pipeline.py", line 413, in __call__
    self.unet.to('cuda')
  File "/opt/anaconda3/envs/ldm/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1194, in _call_impl
    return forward_call(*input, **kwargs)
  File "/data/vjuicefs_hz_cv_enhance_v1/11103392/code/ldm/text-to-image/diffusers/src/diffusers/models/unet_2d_condition.py", line 335, in forward
    sample = self.conv_in(sample)
  File "/opt/anaconda3/envs/ldm/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1194, in _call_impl
    return forward_call(*input, **kwargs)
  File "/opt/anaconda3/envs/ldm/lib/python3.8/site-packages/torch/nn/modules/conv.py", line 463, in forward
    return self._conv_forward(input, self.weight, self.bias)
  File "/opt/anaconda3/envs/ldm/lib/python3.8/site-packages/torch/nn/modules/conv.py", line 459, in _conv_forward
    return F.conv2d(input, weight, bias, self.stride,
RuntimeError: Input type (float) and bias type (c10::Half) should be the same

How to solve this problem?

**Comment by yuxu915** [comment]
@howardgriffin hi, meet the same question, I'd like to ask any idea to solve it? Really thanks!
